markdown: redcarpet
baseurl: /multilingual
exclude: ['README.md']
	  
defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      layout: default
  -
    scope:
      path: _posts/sl
    values:
      lang: sl