markdown: redcarpet
baseurl: /multilingual
exclude: ['README.md']

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/sl
    values:
      lang: sl
