markdown: redcarpet
baseurl: /multilingual
exclude: ['README.md']

#defaults:
  #-
    #scope:
      #path: _posts/en
    #values:
      #layout: default
      #lang: en
  #-
    #scope:
      #path: _posts/sl
    #values:
      #layout: default
      #lang: sl
	  
	  
defaults:
  -
    scope:
      path: ""
    values:
      lang: en
      layout: default
  -
    scope:
      path: _posts/sl
    values:
      lang: sl